
POST http://localhost:5000/api/contacts
Content-Type: application/json

{
  "name":"SHourya REST",
  "email":"go@gmail.com",
  "phone":"1234567867"
}

# GET all
GET http://localhost:5000/api/contacts




